"""
world_state_updater.py

Deterministic world state updater — no LLM involved.
Reads the quest steps generated by the LLM and applies each action's
effects to the world state dict. Fast and logically consistent.

Supported actions:
  MOVE, PICKUP, DROP, GIVE_ITEM, UNLOCK, REPAIR,
  TURN_POWER_ON, FORTIFY, SYNTHESIZE_CURE, USE_CURE,
  TALK, WALK_AROUND (no-ops)
"""

import copy


# =============================================================================
# HELPERS
# =============================================================================

def _get_character(world_state: dict, name: str) -> dict | None:
    """Return the player or NPC dict by name, or None if not found."""
    if name == "player":
        return world_state.get("player")
    for npc in world_state.get("npcs", []):
        if npc["name"] == name:
            return npc
    return None


def _get_location(world_state: dict, name: str) -> dict | None:
    """Return the location dict by name, or None if not found."""
    for loc in world_state.get("locations", []):
        if loc["name"] == name:
            return loc
    return None


def _get_item(world_state: dict, name: str) -> dict | None:
    """Return the item dict by name from the global items list, or None."""
    for item in world_state.get("items", []):
        if item["name"] == name:
            return item
    return None


def _get_object(world_state: dict, name: str) -> dict | None:
    """Return the object dict (e.g. boat) by name, or None."""
    for obj in world_state.get("objects", []):
        if obj["name"] == name:
            return obj
    return None


def _remove_from_inventory(character: dict, item_name: str) -> bool:
    """Remove an item from a character's inventory. Returns True if found."""
    inv = character.get("inventory", [])
    if item_name in inv:
        inv.remove(item_name)
        return True
    return False


def _add_to_inventory(character: dict, item_name: str) -> None:
    character.setdefault("inventory", []).append(item_name)


def _remove_condition(entity: dict, condition: str) -> None:
    conds = entity.get("conditions", [])
    if condition in conds:
        conds.remove(condition)


def _add_condition(entity: dict, condition: str) -> None:
    conds = entity.setdefault("conditions", [])
    if condition not in conds:
        conds.append(condition)


# =============================================================================
# ACTION HANDLERS
# =============================================================================

def apply_move(world_state: dict, params: dict) -> list[str]:
    actor_name = params.get("actor")
    to_loc     = params.get("to")
    actor      = _get_character(world_state, actor_name)
    if not actor:
        return [f"MOVE: actor '{actor_name}' not found"]
    actor["location"] = to_loc
    return []


def apply_pickup(world_state: dict, params: dict) -> list[str]:
    actor_name = params.get("actor")
    item_name  = params.get("item")
    actor      = _get_character(world_state, actor_name)
    item       = _get_item(world_state, item_name)
    if not actor:
        return [f"PICKUP: actor '{actor_name}' not found"]
    if not item:
        return [f"PICKUP: item '{item_name}' not found"]
    item["location"] = None          # remove from world
    _add_to_inventory(actor, item_name)
    return []


def apply_drop(world_state: dict, params: dict) -> list[str]:
    actor_name = params.get("actor")
    item_name  = params.get("item")
    place      = params.get("place")
    actor      = _get_character(world_state, actor_name)
    item       = _get_item(world_state, item_name)
    if not actor:
        return [f"DROP: actor '{actor_name}' not found"]
    if not item:
        return [f"DROP: item '{item_name}' not found"]
    _remove_from_inventory(actor, item_name)
    item["location"] = place
    return []


def apply_give_item(world_state: dict, params: dict) -> list[str]:
    actor_name  = params.get("actor")
    item_name   = params.get("item")
    target_name = params.get("target")
    actor       = _get_character(world_state, actor_name)
    target      = _get_character(world_state, target_name)
    if not actor:
        return [f"GIVE_ITEM: actor '{actor_name}' not found"]
    if not target:
        return [f"GIVE_ITEM: target '{target_name}' not found"]
    if not _remove_from_inventory(actor, item_name):
        return [f"GIVE_ITEM: item '{item_name}' not in {actor_name}'s inventory"]
    _add_to_inventory(target, item_name)
    return []


def apply_unlock(world_state: dict, params: dict) -> list[str]:
    actor_name  = params.get("actor")
    key_item    = params.get("key_item")
    target_place = params.get("target_place")
    actor       = _get_character(world_state, actor_name)
    location    = _get_location(world_state, target_place)
    if not actor:
        return [f"UNLOCK: actor '{actor_name}' not found"]
    if not location:
        return [f"UNLOCK: location '{target_place}' not found"]
    if not _remove_from_inventory(actor, key_item):
        return [f"UNLOCK: key '{key_item}' not in {actor_name}'s inventory"]
    _remove_condition(location, "locked")
    actor["location"] = target_place
    return []


def apply_repair(world_state: dict, params: dict) -> list[str]:
    actor_name   = params.get("actor")
    toolkit_item = params.get("toolkit_item")
    wood_item    = params.get("wood_item")
    target       = params.get("target")
    actor        = _get_character(world_state, actor_name)
    obj          = _get_object(world_state, target)
    if not actor:
        return [f"REPAIR: actor '{actor_name}' not found"]
    if not obj:
        return [f"REPAIR: object '{target}' not found"]
    errors = []
    if not _remove_from_inventory(actor, toolkit_item):
        errors.append(f"REPAIR: toolkit '{toolkit_item}' not in {actor_name}'s inventory")
    if not _remove_from_inventory(actor, wood_item):
        errors.append(f"REPAIR: wood '{wood_item}' not in {actor_name}'s inventory")
    if errors:
        return errors
    obj["state"] = "fixed"
    return []


def apply_turn_power_on(world_state: dict, params: dict) -> list[str]:
    actor_name   = params.get("actor")
    fuse_item    = params.get("fuse_item")
    target_place = params.get("target_place")
    actor        = _get_character(world_state, actor_name)
    location     = _get_location(world_state, target_place)
    if not actor:
        return [f"TURN_POWER_ON: actor '{actor_name}' not found"]
    if not location:
        return [f"TURN_POWER_ON: target location '{target_place}' not found"]
    if not _remove_from_inventory(actor, fuse_item):
        return [f"TURN_POWER_ON: fuse '{fuse_item}' not in {actor_name}'s inventory"]
    _remove_condition(location, "no_power")
    _add_condition(location, "power_on")
    return []


def apply_fortify(world_state: dict, params: dict) -> list[str]:
    actor_name = params.get("actor")
    wood_item  = params.get("wood_item")
    place      = params.get("place")
    actor      = _get_character(world_state, actor_name)
    location   = _get_location(world_state, place)
    if not actor:
        return [f"FORTIFY: actor '{actor_name}' not found"]
    if not location:
        return [f"FORTIFY: location '{place}' not found"]
    if not _remove_from_inventory(actor, wood_item):
        return [f"FORTIFY: wood '{wood_item}' not in {actor_name}'s inventory"]
    _add_condition(location, "fortified")
    return []


def apply_synthesize_cure(world_state: dict, params: dict) -> list[str]:
    actor_name = params.get("actor")
    actor      = _get_character(world_state, actor_name)
    if not actor:
        return [f"SYNTHESIZE_CURE: actor '{actor_name}' not found"]
    # Find and consume any cure_sample in inventory
    cure_sample = next(
        (i for i in actor.get("inventory", []) if "cure_sample" in i), None
    )
    if not cure_sample:
        return [f"SYNTHESIZE_CURE: no cure_sample in {actor_name}'s inventory"]
    _remove_from_inventory(actor, cure_sample)
    # Add antidote_1 to inventory
    _add_to_inventory(actor, "antidote_1")
    return []


def apply_use_cure(world_state: dict, params: dict) -> list[str]:
    actor_name  = params.get("actor")
    item_name   = params.get("item")
    target_name = params.get("target")
    actor       = _get_character(world_state, actor_name)
    target      = _get_character(world_state, target_name)
    if not actor:
        return [f"USE_CURE: actor '{actor_name}' not found"]
    if not target:
        return [f"USE_CURE: target '{target_name}' not found"]
    if not _remove_from_inventory(actor, item_name):
        return [f"USE_CURE: item '{item_name}' not in {actor_name}'s inventory"]
    _remove_condition(target, "infected")
    _remove_condition(target, "injured")
    _add_condition(target, "healthy")
    return []


def apply_supply(world_state: dict, params: dict) -> list[str]:
    actor_name       = params.get("actor")
    food_supplies    = params.get("food_supplies") or params.get("item")
    target_name      = params.get("target")
    actor            = _get_character(world_state, actor_name)
    if not actor:
        return [f"SUPPLY: actor '{actor_name}' not found"]
    if food_supplies and not _remove_from_inventory(actor, food_supplies):
        return [f"SUPPLY: '{food_supplies}' not in {actor_name}'s inventory"]
    return []


# No-ops — these actions have no world state effect
def apply_noop(world_state: dict, params: dict) -> list[str]:
    return []


# =============================================================================
# DISPATCH TABLE
# =============================================================================

ACTION_HANDLERS = {
    "MOVE":            apply_move,
    "PICKUP":          apply_pickup,
    "DROP":            apply_drop,
    "GIVE_ITEM":       apply_give_item,
    "UNLOCK":          apply_unlock,
    "REPAIR":          apply_repair,
    "TURN_POWER_ON":   apply_turn_power_on,
    "FORTIFY":         apply_fortify,
    "SYNTHESIZE_CURE": apply_synthesize_cure,
    "USE_CURE":        apply_use_cure,
    "SUPPLY":          apply_supply,
    "TALK":            apply_noop,
    "WALK_AROUND":     apply_noop,
}


# =============================================================================
# MAIN UPDATE FUNCTION
# =============================================================================

def apply_chapter_to_world_state(
    world_state: dict,
    chapter: dict,
) -> tuple[dict, list[str]]:
    """
    Apply all steps from a generated chapter to the world state.

    Returns:
        updated_world_state — a deep copy with all changes applied
        errors              — list of any logical issues encountered
    """
    updated = copy.deepcopy(world_state)
    # unwrap top-level "world_state" key if present
    ws = updated.get("world_state", updated)
    all_errors = []

    for quest in chapter.get("quests", []):
        for step in quest.get("steps", []):
            action   = step.get("action", "").upper()
            # merge step-level fields with parameters to handle both formats
            params   = {**step, **step.get("parameters", {})}
            step_num = step.get("step")

            handler = ACTION_HANDLERS.get(action)
            if handler is None:
                all_errors.append(f"Step {step_num}: unknown action '{action}'")
                continue

            errors = handler(ws, params)
            for err in errors:
                all_errors.append(f"Step {step_num}: {err}")

    return updated, all_errors
